[ERROR] There is a conflict between multiple rules for assigning the same variable.
[ERROR] 
[ERROR] This value is available because the justification of its definition is true:
[ERROR]   --> test_scope/sub_sub_scope.catala
[ERROR]    | 
[ERROR] 24 |   def y [ a2.x = 1 ] := 1
[ERROR]    |           ^^^^^^^^
[ERROR] 
[ERROR] This value is available because the justification of its definition is true:
[ERROR]   --> test_scope/sub_sub_scope.catala
[ERROR]    | 
[ERROR] 25 |   def y [ a2.x + 1 = 2 ] := 1
[ERROR]    |           ^^^^^^^^^^^^
